config/routes.rb
Bucks::Application.routes.draw do

  
  devise_for :users

  devise_for :students

  get "/users/sign_up", to: "registrations#new", as: :sign_up

  get "/home", to: "bucks#home"  

  get "bucks/about_us"

  get "bucks/faq"

  get "bucks/contact_us"

  get "bucks/terms_of_service"

  get "bucks/privacy_policy"

end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bucks_controller.rb
class BucksController < ApplicationController
  def home
  end

  def about_us
  end

  def faq
  end

  def contact_us
  end

  def terms_of_service
  end

  def privacy_policy
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about_us
  end

  def faq
  end

  def contact_us
  end

  def terms_of_service
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bucks_helper.rb
module BucksHelper
end

app/views/bucks/about_us.html.erb
<h1>What is Bootcamp Bucks?</h1>
<p>Bootcamp Bucks was created by a team of n00bs from the DevPoint Labs Winter 2014 class. As much as we wanted to learn Ruby on Rails, we felt the pain of the finanical responsibility needed to take a development bootcamp. Our goal is to lower the barrier to entry for more students to gain a working knowledge of the technology software skills needed to succeed in today's work environment. Bootcamp Bucks is located in Salt Lake City, UT.</p>

app/views/bucks/contact_us.html.erb
<h1>Contact Us</h1> 

<p>Form will go here</p>

app/views/bucks/faq.html.erb
<h1>StaticPages#faq</h1>
<p>Find me in app/views/static_pages/faq.html.erb</p>

app/views/bucks/find_your_rate.html.erb
<h1>Find Your Rate</h1>

app/views/bucks/home.html.erb
<h1>Financial Aid for your development bootcamp</h1>
<h2>Become a software developer and increase your earnings potential!</h2>
<p button type="button" class="btn btn-primary">Get Started</button></p>

app/views/bucks/privacy_policy.html.erb
<h1>Privacy Policy</h1>
<p>This Privacy Policy explains the practices of Bootcamp Bucks, Inc. and their affiliates (together, "Bootcamp Bucks", "we", or "us") with respect to how we collect, use, disclose and secure your personal information in connection with the Bootcamp Bucks website at www.bootcampbucks.com ("Website") and Bootcamp Bucks's lending and social networking service or related services ("Service"). This Privacy Policy applies to personal information we collect from you and from third parties, but does not apply to any personal information collected by third parties from you. If you are a current Bootcamp Bucks customer, please see our Privacy Notice for a comprehensive explanation of how we collect, use and share your personal information and what you can do to limit the use and sharing of your information.</p>

<h2>Changes in Privacy Policy</h2>
<p>This notice describes our Privacy Policy effective as of the date indicated above. Bootcamp Bucks reserves the right to change this Privacy Policy at any time so please review it frequently. We will provide notice of changes by indicating on the Privacy Policy the date it was last updated and making such updated Privacy Policy available on the Website. We may also choose to notify you of material changes to the Privacy Policy by email or by means of a notice on our home page.</p>

<h2>Collecting personal information</h2>
<p>We may collect personal information about you from you and from third parties, including personal, demographic and aggregate data. As used in this Privacy Policy, "personal information" means information that specifically identifies you, including, but not limited to, your name, address, telephone number, email address, social security number, driver's license number, bank account numbers, student loan account numbers, employment info, credit card number, and student identification number. Demographic information is anonymous information, which may include your age, date of birth, income, gender, geographic area, hobbies or interests. Demographic information is not considered personal information unless it is linked with your other personal information, which we may do for a variety of reasons such as customizing content or services according to your interests and preferences or verifying your identity. Personal information does not include aggregate information, which is data we collect about the use of the Website or Service (or categories of the Website or Service), from which personal information has been removed. Aggregate data are used for a number of purposes such as helping us understand trends and user needs so we can improve our products and services.</p>

<p>Personal information may be collected in a number of ways, such as when you visit the Website with your Internet browser or use the Service. In addition, Bootcamp Bucks may ask you to provide certain personal information when filling out and submitting loan applications, registration forms or providing feedback to Bootcamp Bucks. When submitting loan applications, registering to view your loan account history, or applying to receive or provide a transfer of funds pursuant to the Service, you may be asked to provide your social security number, a bank routing number, a bank account number, contact information, your name and other personal information. Also, you may post to the Website or transmit to Bootcamp Bucks personal information, photographs, videos, and other content, such as to your social networking profile, through messaging functionality on the Website, or to a public bulletin board, blog, chat room or other forum on the Website. You may control with whom you share your profile information on the Website and you understand that if you choose to share your information, your profile may be generally available on the Website. However, if you are a current borrower, you may not control certain information that you have already agreed to provide to certain investors as described in your promissory note. All such content that you post to the Website is done at your own risk and Bootcamp Bucks bears no responsibility for any such content or any liability for any claims arising out of such content. You should also be aware that any personal information you use on our blog can be used, read, or collected by other users of the blog and could be used to send you unsolicited messages. We are not responsible for personal information you choose to submit in the blog or any other area of the website.</p>

<p>When you use the Website, Bootcamp Bucks may also collect certain information about your computer to facilitate and evaluate your use of the Website and the Service. For example, we may log environmental variables, such as browser type, operating system, referring or exit web pages, and the Internet Protocol (IP) address of your computer. We may on occasion supplement the personal information you submit to us with information from third-party sources. For example, if permitted under applicable law, we may supplement your Registration Information (defined below) with address standardization data to verify the address you have entered is actually your address.</p>

<p>We do not intend to collect personal information from children under 13 years of age. If we learn that we have collected this information from a child under the age of 13, we will promptly take all reasonable steps to delete the data from our system.</p>

<h2>Use of personal information</h2>
<p>In general, we use personal information to provide you with information or services you request, to inform you about other information and services we think will be of interest to you, to facilitate your use and our administration and operation of the Website and the Service, to learn more about and improve the Website and the Service, and for the purpose for which the information was provided.</p>

<h2>Sharing your personal information</h2>
<p>We only share your personal information with unaffiliated third parties as permitted or required by law. When we share your personal information with vendors and service providers who perform functions on our behalf, we require that they keep your information confidential and secure, and that they use it only as is reasonably necessary to carry out their work or comply with applicable law. In addition, personal information may be disclosed or transferred to our affiliates and as part of, or during negotiations of, a merger, consolidation, sale of company assets or equity, financing, acquisition, strategic alliance or in any other situation where personal information may be transferred as one of the business assets of Bootcamp Bucks. Bootcamp Bucks does not share, rent, or trade your personal information with third parties for their promotional purposes.<p>

<h2>Protecting your personal information</h2>
<p>We maintain administrative, technical and physical safeguards designed to protect the security, confidentiality and integrity of your personal information. The personal information that you provide online in connection with registering yourself as a user of the Website or of the Service or use the Service is protected in several ways. Access by you to such personal information is available through a password and unique customer ID selected by you. This password is encrypted. To protect the confidentiality of such personal information, you should not divulge your password to anyone. You are responsible for all uses of the Website and Service by any person using your customer ID and password. Please advise us immediately if you believe your password has been compromised. In addition, your personal information resides on servers or in areas of facilities that only selected Bootcamp Bucks personnel and contractors have access to. Bootcamp Bucks encrypts all data that you submit to Bootcamp Bucks through the Website, and thereby attempts to prevent unauthorized parties from viewing such information during transmission to Bootcamp Bucks. Please note that any information you submit by email may not be secure, so please do not send any sensitive information or materials in or attached to any email to Bootcamp Bucks. Bootcamp Bucks will never request that you submit sensitive information over email; please report any such requests purporting to originate from Bootcamp Bucks to us.</p>

<p>Please note that any information, photos, contact information, email addresses, videos, and other content you post to your social networking profile or to any public bulletin board, blog, chat room or other forum is available to all persons accessing that location. The information you share would then be available to all persons accessing these venues, and such information may be read, collected or used by others for any purpose, including sending you unsolicited messages. Bootcamp Bucks is not responsible for any information you elect to submit in these venues or the use of such information.</p>

<h2>Your choices regarding your personal information</h2>
<p>Personal information that is not collected on the Website or in connection with the Service is not generally subject to this Privacy Policy. The Website may contain links to other websites at which personal information is collected. For example, Bootcamp Bucks may have relationships with various service providers whose services are available to you from the Website, from websites that are linked to the Website, or in connection with the Service. Typically, these providers offer services that Bootcamp Bucks customers might find useful, such as those that can be used in conjunction with Service. In order to use those providers' services, you may be required to provide personal information to the providers. Unless expressly provided to the contrary, the collection, use, disclosure and security of your personal information will be governed by the privacy policy applicable to that website, and not by this Privacy Policy.</p>

<h2>Tracking, use of cookies, web beacons and similar tracking devices</h2>
<p>In order to improve our Service and the Website and provide more convenient, relevant experiences to our customers, we and our vendors may use "cookies" and similar devices to track your activities. A cookie is small amount of data that is transferred to your browser by servers within the domain and can only be read by the server that gave it to you. It functions as your identification card and enables Social Finance to record your passwords, purchases and preferences. A web beacon is a small transparent gif image that is embedded in an HTML page or email used to track when the page or email has been viewed. A similar device may be used by which a product, service or functionality may send data to a server when a set of user-initiated events occur (such as after clicking a button on the Website or in an email). This device is similar to a cookie in that it tracks your visit and the data can only be read by the server that receives the data. It is different than a cookie in that it is not browser-based, may not function as an identification card and does not store any data on your computer. While Bootcamp Bucks uses cookies and similar devices to track your use of the Website and the Service, such as the number of downloads, types of Service used, and how many users we receive daily, and while our web servers automatically log the IP/Internet address of your computer, Social Finance does not generally use this information to identify you personally. However, if you expressly provide consent for the Website or the Service to "remember" you when you log into your account, that unique identifier will be stored on a cookie on your computer and that unique identifier will be linked to your Registration Information. As a result, your navigation path around the Website and the Service will be tracked.<p>

<p>Most browsers are initially set to accept cookies and similar devices. You can set your browser to notify you when you receive a cookie or similar device, giving you the chance to decide whether or not to accept it. (For some web pages that require an authorization, cookies are not optional. Users choosing not to accept cookies or similar devices will probably not be able to access those pages or the related products and services.)</p>

<h2>Information from Advertisements on Other Websites</h2>
<p>We place and track advertisements on third-party websites. Like many advertisers, we advertise our products and services, and we contract with third parties to place advertisements, on websites not affiliated with us where we think the advertisements are likely to be most relevant. These advertisements may contain cookies or other mechanisms that allow tracking of your response to our ads. We and our contracted third parties track and report performance of our advertising and marketing campaigns by using cookies, web beacons, and other similar technology, which may be used to collect and store information about user visits, page visits and duration, and the specific ad or link that the user clicked on to visit the site. No personally identifiable information is stored during this process.</p>

<h2>Contacting Bootcamp Bucks</h2>
<p>If you have questions regarding our Privacy Policy or if you believe that Bootcamp Bucks has not complied with this Privacy Policy with respect to your personal information, please contact us at info@bootcampbucks.com. If you are reporting noncompliance with this Privacy Policy, in your e-mail or letter, please describe in as much detail as possible (but without disclosing any sensitive information about you or third parties) the ways in which you believe that the Privacy Policy has not been complied with.</p>

app/views/bucks/terms_of_service.html.erb
<h1>Terms of Use</h1>
<p>Thank you for using www.bootcampbucks.com (the "Website"). By using this Website, you are agreeing to be bound by the Terms of Use described below, so please read them very carefully. IF YOU DO NOT WISH TO BE BOUND BY THESE TERMS OF USE, YOU MAY NOT ACCESS OR USE THE WEBSITE. These Terms of Use are provided on behalf of Bootcamp Bucks, Inc. ("Bootcamp Bucks", "we", or "us").
</p>

<h2>Privacy</h2>
<p>Your privacy is very important to us. Our privacy policy explains how we treat your personal information and protect your privacy when you use our Website. We will not share or sell any of your information with any third party, except as specifically described in our privacy policy, which is hereby incorporated by reference into these Terms of Use.</p>

<h2>Information Sharing and Social Features</h2>
<p>You may have the opportunity to share content or information, including, but not limited to, your name, email address, or other information that you provide via the Website, with other users of the Website. By sharing information or content on the Website, you expressly agree to all of the following:</p>

<p>You grant Bootcamp Bucks a non-exclusive, transferable, sub-licensable, royalty-free, worldwide license to use any information or content that you post on or in connection with your use of the Website, subject to the privacy provisions described in our privacy policy.
You understand that deleted content or information may continue to exist on our servers or in backup copies that we maintain for our own use.
You will not post content or take any action on the Website that may constitute libel or slander, infringes or violates someone else's rights, that is protected by any copyright or trademark, or otherwise violates the law.
Content and information that you share will be available to other users of our Website. You understand that such third parties may access, use, store and transfer such content and information and to associate it with you.
You agree that you will not use the Website for commercial purposes.
We may remove any content or information that you share on the Website for any reason.
You agree that you will not use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on our Website.</p>

<h2>Loan Pre-Registrations and Applications</h2>
<p>You may be presented with the opportunity to pre-register and/or apply for a loan through the Website. When pre-registering or applying for a loan on the Website, you agree to provide current, complete, and accurate information about yourself. If any information you provide is untrue, inaccurate, not current, or incomplete, Bootcamp Bucks has the right to terminate your loan pre-registration and/or application and to decline to provide any and all future use of the Website. We reserve the right to decline your application for a loan.</p>

<h2>Your Account</h2>
<p>You may be required to create an Account to use of the certain parts of the Website. When you create an account, you will be required to pick a user name and a password. You may not disclose your user name or password to any third party. If you learn of any unauthorized use of your password or account, please contact us immediately.</p>

<h2>Changes and Modifications</h2>
<p>Bootcamp Bucks reserves the right to temporarily or permanently modify or discontinue the Website, or any portion of the Website, for any reason, at our sole discretion, and without notice to you. Bootcamp Bucks may also change the Terms of Use from time to time without notice to you. Please review these Terms of Use from time to time, because your continued access or use of the Website after any modifications have become effective shall be deemed your conclusive acceptance of the modified Terms of Use.</p>

<h2>Links</h2>
<p>This Website may contain links to websites maintained by non-affiliated third parties. Such websites may have Terms of Use, Privacy Policies, or security practices that are different from those of Bootcamp Bucks. Bootcamp Bucks does not endorse or recommend, and hereby disclaims any liability for, any information or products offered at such websites.</p>

<h2>No Warranty</h2>
<p>Bootcamp Bucks does not warrant the accuracy, adequacy or completeness of the information provided herein and expressly disclaims liability for any errors or omissions in such information. No warranty of any kind, implied, expressed or statutory including but not limited to the warranties of non-infringement of third party rights, title, merchantability, fitness for a particular purpose and freedom from computer virus, is given in conjunction with the information. Calculators and tools on the Site provide you with ESTIMATES that may be different than actual amounts.</p>

<h2>Limitation of Liability</h2>
<p>You agree that all access and use of the Website and its contents is at your own risk. In no event shall Bootcamp Bucks be held liable for any damages, including without limitation direct or indirect, special, incidental, or consequential damages, losses or expenses arising in connection with the Website or any linked site or use thereof or inability to use by any party, or in connection with any failure of performance, error, omission, interruption, defect, delay in operation or transmission, computer virus or line or system failure, even if Bootcamp Bucks, or representatives thereof, are advised of the possibility of such damages, losses or expenses.</p>

<h2>Privacy</h2>
<p>Our privacy policy explains how we treat your personal information and protect your privacy when you use our Website. Our privacy policy is hereby incorporated by reference into these Terms of Use.</p>

<h2>Applicable Law</h2>
<p>You agree to abide by all applicable local, state, national, and international laws and regulations in your use of the Website. Our Website is available only to individuals who are permitted to use it under applicable law. If you do not qualify, please do not use our Website. You agree to be solely responsible for your actions and the contents of your transmissions through the Website. You agree not to impersonate any person or entity or falsely state or otherwise misrepresent your identity or affiliation with a person or entity. You represent and warrant that you possess the legal right and ability to enter into these Terms of Use and to use the Website in accordance with these Terms of Use. Unauthorized use of this Website, including but not limited to unauthorized entry into Bootcamp Bucks’ systems, misuse of passwords, or misuse of any information posted on a site, is strictly prohibited.</p>

<p>These Terms of Use shall be governed in all respects by the substantive laws of the State of Utah, without regard to its provisions relating to conflict of laws. You and Bootcamp Bucks agree to submit to the personal and exclusive jurisdiction and venue of the state and federal courts located within Salt Lake County, Utah. The failure of Bootcamp Bucks to exercise or enforce any right or provision of the Terms of Use shall not constitute a waiver of such right or provision. If any provision of the Terms of Use is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the Terms of Use remain in full force and effect. You agree that regardless of any statute, regulation, or law to the contrary, any claim or cause of action arising out of or related to use of the site or the Terms must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>

<p>Please direct all questions or comments about these Terms of Use to info@bootcampbucks.com</p>

<p>COPYRIGHT © Bootcamp Bucks, Inc. ALL RIGHTS RESERVED.</p>

<p>Bootcamp Bucks owns the copyright in all of the information and material contained in this Website. The contents of the website, including its "look and feel" (e.g., text, graphics, images, logos, and button icons), editorial content, notices, software (including html-based computer programs), and other material are protected under both United States and foreign copyright, patent, trademark, and other laws. Your right to use the Website is personal to you. You agree not to reproduce, duplicate, copy, sell, resell, use or exploit for any commercial purposes, the Website or use of or access to the Website or any information or technology obtained from the Website.</p>

app/views/layouts/_message.html.erb
<section id="content">
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
      <div class="container">
      <div class="jumbotron"
      <%= yield %>
    </div>
  </div>

app/views/layouts/_navigation_bar.html.erb
<!-- Top Navbar -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li><%= link_to "Bootcamp Bucks", home_path %></li>
      <li><%= link_to "About Us", bucks_about_us_path %></li>
      <li><%= link_to "FAQ", bucks_faq_path %></li>
      <li><%= link_to "Contact Us", bucks_contact_us_path %></li>
    </ul>


      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li>

            <%= link_to edit_user_registration_path(current_user) do %>
              <%= image_tag( current_user.profile_picture.url(:tiny), class: 'img-circle' ) %>
              <%= [current_user.first_name, current_user.last_name].join(' ') %>
            <% end %>
          </li>
          <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
          <li> <%= link_to "Sign In", user_session_path %> </li>
        <% end %>
      </ul>
  </div><!-- /.container-fluid -->
</nav>

<!-- Footer Navigation -->
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Terms of Service", bucks_terms_of_service_path %></li>
      <li><%= link_to "Privacy Policy", bucks_privacy_policy_path %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bucks</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= render 'layouts/navigation_bar' %>

  </head>

  <body>
    <%= render 'layouts/message' %>
  </body>
</html>